use `stock`;

-- 用户表
CREATE TABLE IF NOT EXISTS  `user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '名称',
  `username` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户名',
  `password` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码',
  `create_time` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_time` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '编辑时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT COMMENT='用户表';

-- 商品分类表
CREATE TABLE IF NOT EXISTS  `category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '名称',
  `create_time` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_time` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '编辑时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT COMMENT='商品分类表';

-- 商品表
CREATE TABLE IF NOT EXISTS  `goods` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '名称',
  `category_id` INT(11) NOT NULL DEFAULT 0 COMMENT '商品分类ID',
  `price` DECIMAL(8,2) NOT NULL DEFAULT 0.00 COMMENT '价格',
  `amount` DECIMAL(8,2) NOT NULL DEFAULT 0.00 COMMENT '数量',
  `unit` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '单位',
  `create_time` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_time` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '编辑时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT COMMENT='商品表';

-- 商品入库表
CREATE TABLE IF NOT EXISTS  `goods_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '名称',
  `goods_id` INT(11) NOT NULL DEFAULT 0 COMMENT '商品ID',
  `price` DECIMAL(8,2) NOT NULL DEFAULT 0.00 COMMENT '价格',
  `amount` DECIMAL(8,2) NOT NULL DEFAULT 0.00 COMMENT '数量',
  `create_time` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_time` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '编辑时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT COMMENT='商品入库表';

-- 订单表
CREATE TABLE IF NOT EXISTS  `order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `buyer_id` INT(11) NOT NULL DEFAULT 0 COMMENT '客户ID',
  `total` DECIMAL(8,2) NOT NULL DEFAULT 0.00 COMMENT '总价',
  `create_time` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_time` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '编辑时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT COMMENT='订单表';

-- 订单商品表
CREATE TABLE IF NOT EXISTS  `order_goods` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '名称',
  `goods_id` INT(11) NOT NULL DEFAULT 0 COMMENT '商品ID',
  `order_id` INT(11) NOT NULL DEFAULT 0 COMMENT '订单ID',
  `price` DECIMAL(8,2) NOT NULL DEFAULT 0.00 COMMENT '价格',
  `amount` DECIMAL(8,2) NOT NULL DEFAULT 0.00 COMMENT '数量',
  `unit` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '单位',
  `create_time` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_time` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '编辑时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT COMMENT='订单商品表';

-- 客户表
CREATE TABLE IF NOT EXISTS  `buyer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '名称',
  `phone` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '电话',
  `create_time` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '创建时间',
  `update_time` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '编辑时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT COMMENT='客户表';